ALTER TABLE "ach"."achievement" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."achievement" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."achievement" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."achievement_workout_type" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."achievement_workout_type" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."achievement_workout_type" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."ach_level" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."ach_level" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "ach"."ach_level" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."period" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."period" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."period" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."quantity_unit" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."quantity_unit" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "cfg"."quantity_unit" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "iam"."api_key" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "iam"."api_key" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "iam"."api_key" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement_progress" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement_progress" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_achievement_progress" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."user" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."user" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."user" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_workout" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_workout" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_workout" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "usr"."usr_workout" ADD COLUMN "achievement_processed_at" timestamp;--> statement-breakpoint
ALTER TABLE "wrk"."workout_type" ADD COLUMN "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "wrk"."workout_type" ADD COLUMN "created_by" integer DEFAULT -1 NOT NULL;--> statement-breakpoint
ALTER TABLE "wrk"."workout_type" ADD COLUMN "updated_by" integer DEFAULT -1 NOT NULL;